joint_limits:
  arm_5_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  arm_6_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_joint_gripper_right:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  arm_4_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_joint_gripper_left:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  arm_3_joint:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0