# Gripper Controller -----------------------------------------------------------
gripper_controller:
    type: "position_controllers/GripperActionController"
    joint: gripper_base_joint_gripper_left


