# Mode controllers used to switch between control methods ----------------------------
velocity_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 2 # velocity


# Velocity - Right and Left Joint Velocity Trajectory Controllers -------------------
arm_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint

    constraints:
      goal_time: 2.0 # Defaults to zero
      stopped_velocity_tolerance: 0.4 # Defaults to 0.01
      arm_1_joint:
        trajectory: 0
        goal: 0.2
      arm_2_joint:
        trajectory: 0
        goal: 0.2
      arm_3_joint:
        trajectory: 0
        goal: 0.2
      arm_4_joint:
        trajectory: 0
        goal: 0.2
      arm_5_joint:
        trajectory: 0
        goal: 0.2
      arm_6_joint:
        trajectory: 0
        goal: 0.2

    gains:
      arm_1_joint: {p: 2.0, i: 0.01, d: 1.0, i_clamp: 1}
      arm_2_joint: {p: 3.0, i: 0.01, d: 1.0, i_clamp: 1}
      arm_3_joint: {p: 3.0, i: 0.01, d: 1.0, i_clamp: 1}
      arm_4_joint: {p: 3.0, i: 0.01, d: 1.0, i_clamp: 1}
      arm_5_joint: {p: 3.0, i: 0.01, d: 1.0, i_clamp: 1}
      arm_6_joint: {p: 3.0, i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5


